### ISSUE TITLE
run project

### ISSUE THREAD

**Issue by teh23** [discosultan/juno#189]
Hey,

i run start_dashboard.sh sucessful but when i was run i got the error
![Capture](https://user-images.githubusercontent.com/14942614/101491578-35f9ac80-3964-11eb-83eb-e5990989e586.PNG)

i thought it is problem with web service so i tested it by postman and got " "message": "Rejection(BodyDeserializeError { cause: Error(\"invalid number\", line: 1, column: 2) })"" and im not sure what im doing wrong :/

**Comment by discosultan** [comment]
Hey @teh23, sorry for the trouble. The project is very much in development and not intended for public use. I've updated the README accordingly.
